import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { SectionTitle } from "@/components/common/SectionTitle";
import { CampaignImageBlock } from "@/components/sections/CampaignImageBlock";
import { DonationInfoCard } from "@/components/cards/DonationInfoCard";
import { donationFaqs, donationGuides } from "@/data/donation";
import { siteConfig } from "@/data/site";

export const metadata: Metadata = { title: "정연우 후원회 | 정연우.kr", description: "정연우후원회 남구청장선거 후원 안내입니다." };
export default function DonationPage() { return <><section className="campaign-gradient py-16"><div className="container-page"><p className="inline-flex rounded-full bg-white px-4 py-2 text-sm font-black text-[#0052B8]">후원회</p><h1 className="mt-5 text-4xl font-black tracking-tight text-[#11205A] md:text-6xl">정연우 후원회</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#344054]">남구의 새로운 변화를 함께 만들어 주세요.</p><div className="mt-8"><CampaignImageBlock src={siteConfig.images.donationBanner} alt="정연우후원회 남구청장선거 후원 안내 배너" title="정연우후원회" description="후원 정보는 아래 HTML 카드에서도 정확히 확인하실 수 있습니다." /></div></div></section><section className="py-16"><div className="container-page grid gap-8 lg:grid-cols-[0.9fr_1.1fr]"><DonationInfoCard /><div><SectionTitle eyebrow="후원 안내" title="소중한 정성을 투명하게 관리하겠습니다" description="남구의 지역자치, 문화예술, 미래세대를 위한 변화에 함께해 주세요." /><ul className="mt-8 grid gap-3">{donationGuides.map((guide) => <li key={guide} className="flex gap-2 rounded-2xl bg-[#F8FAFC] px-4 py-3 text-sm leading-6 text-[#344054]"><CheckCircle2 size={17} className="mt-1 shrink-0 text-[#0052B8]" />{guide}</li>)}</ul><p className="mt-6 rounded-2xl bg-[#FFF7D6] p-4 text-sm font-bold leading-7 text-[#344054]">본 페이지의 후원 안내는 후원회 안내를 바탕으로 구성되었습니다. 후원 전 세부 자격과 한도는 후원회 또는 선거관리위원회 안내를 확인해 주세요.</p></div></div></section><section className="bg-[#F8FAFC] py-16"><div className="container-page"><SectionTitle title="후원회 FAQ" align="center" /><div className="mt-10 grid gap-4 md:grid-cols-2">{donationFaqs.map((faq) => <article key={faq.q} className="rounded-[1.5rem] bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#11205A]">{faq.q}</h2><p className="mt-3 leading-7 text-[#667085]">{faq.a}</p></article>)}</div></div></section></>; }
