import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Music2 } from "lucide-react";
import { SectionTitle } from "@/components/common/SectionTitle";
import { CTASection } from "@/components/common/CTASection";

export const metadata: Metadata = { title: "대명 프로젝트 | 정연우.kr", description: "남구를 대구 문화예술의 심장으로 만드는 정연우 후보의 1호 공약입니다." };
const tasks = ["대명공연거리 활성화", "대명공연예술센터 중간지원조직화", "지역쿼터제 검토", "공연비 선지급제 검토", "다원공연예술 지원"];
const links = ["남구형 문화패스", "골목공연", "주말 문화장터", "청년예술 레지던시"];

export default function DaemyeongPage() {
  return <><section className="blue-gradient py-16 text-white"><div className="container-page"><p className="inline-flex rounded-full bg-[#FFD84D] px-4 py-2 text-sm font-black text-[#11205A]">1호 공약</p><h1 className="mt-5 text-4xl font-black md:text-6xl">대명 프로젝트</h1><p className="mt-5 max-w-3xl text-xl leading-9 text-blue-50">대명동에는 행정이 만든 것이 아니라, 예술가들이 스스로 만든 생태계가 있습니다. 이제 구청이 그 가능성을 제대로 지원해야 합니다.</p></div></section><section className="py-16"><div className="container-page grid gap-8 lg:grid-cols-[0.95fr_1.05fr]"><div><SectionTitle eyebrow="왜 대명인가" title="자생적 예술촌의 힘을 남구 미래로" description="계명대학교 대명캠퍼스 주변으로 공연예술, 극단, 음악, 미술, 기획, 예술교육이 모인 문화예술 기반을 계대네거리에서 명덕역까지 확장하겠습니다." /></div><div className="rounded-[2rem] bg-[#FFF7D6] p-8"><Music2 size={42} className="text-[#0052B8]" /><p className="mt-5 text-3xl font-black text-[#11205A]">대명공연거리와 대명공연예술센터를 남구 청년·예술가 정주의 기반으로 연결하겠습니다.</p></div></div></section><section className="bg-[#F8FAFC] py-16"><div className="container-page"><SectionTitle eyebrow="5대 과제" title="예술가가 계속 활동할 수 있는 구조" align="center" /><div className="mt-10 grid gap-5 md:grid-cols-5">{tasks.map((task) => <article key={task} className="rounded-[1.5rem] bg-white p-5 text-center shadow-sm"><CheckCircle2 className="mx-auto text-[#0052B8]" /><p className="mt-4 font-black text-[#11205A]">{task}</p></article>)}</div></div></section><section className="py-16"><div className="container-page"><SectionTitle eyebrow="문화예술과 상권" title="공연 후 안지랑, 앞산, 대명상권으로 이어지게" description="청년 예술인과 지역 상인이 함께 살아나는 남구형 문화관광 동선을 만들겠습니다." /><div className="mt-8 flex flex-wrap gap-3">{links.map((item) => <span key={item} className="rounded-full bg-[#EAF4FF] px-4 py-2 font-black text-[#0052B8]">{item}</span>)}</div><div className="mt-10 rounded-[2rem] bg-[#11205A] p-8 text-white"><h2 className="text-3xl font-black">예술가를 소비하지 않는 행정</h2><p className="mt-4 text-lg leading-8 text-blue-50">예술을 행사 때 불러 쓰는 방식에서 벗어나, 예술가가 계속 활동할 수 있는 구조를 만들겠습니다.</p></div></div></section><section className="pb-16"><div className="container-page grid gap-4 md:grid-cols-2"><Link href="/map" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#0052B8] px-6 py-4 font-black text-white">공약지도에서 보기<ArrowRight size={18} /></Link><CTASection title="대명 프로젝트에 의견을 더해 주세요" description="현장의 목소리로 문화예술 공약을 더 구체화하겠습니다." href="/voice" buttonLabel="의견 남기기" tone="yellow" /></div></section></>;
}
